### ISSUE TITLE
During execution of production build an error is shown

### ISSUE THREAD

**Issue by gnoesiboe** [freshheads/webpack-config-builder#54]
Below the output during a production deployment for GGZ. It does not actually result in a bad build. It mentions webpack-config-builder, so it might be related.

```bash
[frontend] > ggzstandaarden@ prod:build /home/gijsn/www/ggz-zorgstandaarden/prod-2.8.20/assets/frontend
[frontend] > NODE_ENV=production webpack
[frontend] 
[frontend] npm ERR! missing: @freshheads/react-form-state@git+ssh://git@github.com(opens in new tab)/freshheads/react-form-state.git#semver:^0.2, required by ggzstandaarden@
[frontend] npm ERR! missing: fh-style-standards@git+ssh://git@github.com(opens in new tab)/freshheads/style-standards.git#semver:^2.0.0, required by ggzstandaarden@
[frontend] npm ERR! missing: validate.js@0.12.0, required by @freshheads/react-form-state@git+ssh://git@github.com(opens in new tab)/freshheads/react-form-state.git#33cf529a12412e38aad8312be0c56a8108051407
[frontend] npm ERR! missing: sass-mq@3.3.2, required by fh-style-standards@git+ssh://git@github.com(opens in new tab)/freshheads/style-standards.git#877e9be38984aac63ba5e170ac432f373b890f4c
[frontend] Command 'npm list --json --depth=0 --dev=true --prod=true' resulted in an error. Perhaps there are unmet peer dependencies?
[frontend] { Error: Command failed: npm list --json --depth=0 --dev=true --prod=true
[frontend] npm ERR! missing: @freshheads/react-form-state@git+ssh://git@github.com(opens in new tab)/freshheads/react-form-state.git#semver:^0.2, required by ggzstandaarden@
[frontend] npm ERR! missing: fh-style-standards@git+ssh://git@github.com(opens in new tab)/freshheads/style-standards.git#semver:^2.0.0, required by ggzstandaarden@
[frontend] npm ERR! missing: validate.js@0.12.0, required by @freshheads/react-form-state@git+ssh://git@github.com(opens in new tab)/freshheads/react-form-state.git#33cf529a12412e38aad8312be0c56a8108051407
[frontend] npm ERR! missing: sass-mq@3.3.2, required by fh-style-standards@git+ssh://git@github.com(opens in new tab)/freshheads/style-standards.git#877e9be38984aac63ba5e170ac432f373b890f4c
[frontend] 
[frontend]     at checkExecSyncError (child_process.js:616:11)
[frontend]     at Object.execSync (child_process.js:653:13)
[frontend]     at resolveListOfInstalledRootModules (/home/gijsn/www/ggz-zorgstandaarden/prod-2.8.20/assets/frontend/node_modules/@freshheads/webpack-config-builder/build/utility/moduleHelper.js:35:41)
[frontend]     at checkIfModuleIsInstalled (/home/gijsn/www/ggz-zorgstandaarden/prod-2.8.20/assets/frontend/node_modules/@freshheads/webpack-config-builder/build/utility/moduleHelper.js:13:30)
[frontend]     at Object.validateIfRequiredModuleIsInstalled (/home/gijsn/www/ggz-zorgstandaarden/prod-2.8.20/assets/frontend/node_modules/@freshheads/webpack-config-builder/build/utility/moduleHelper.js:7:10)
[frontend]     at CleanBuildDirectoryAdapter.apply (/home/gijsn/www/ggz-zorgstandaarden/prod-2.8.20/assets/frontend/node_modules/@freshheads/webpack-config-builder/build/adapter/freshheads/CleanBuildDirectoryAdapter.js:6:24)
[frontend]     at Builder.applyAdapter (/home/gijsn/www/ggz-zorgstandaarden/prod-2.8.20/assets/frontend/node_modules/@freshheads/webpack-config-builder/build/Builder.js:25:24)
[frontend]     at currentAdapter.apply (/home/gijsn/www/ggz-zorgstandaarden/prod-2.8.20/assets/frontend/node_modules/@freshheads/webpack-config-builder/build/Builder.js:27:22)
[frontend]     at ResolveAdapter.apply (/home/gijsn/www/ggz-zorgstandaarden/prod-2.8.20/assets/frontend/node_modules/@freshheads/webpack-config-builder/build/adapter/ResolveAdapter.js:11:9)
[frontend]     at Builder.applyAdapter (/home/gijsn/www/ggz-zorgstandaarden/prod-2.8.20/assets/frontend/node_modules/@freshheads/webpack-config-builder/build/Builder.js:25:24)
[frontend]     at currentAdapter.apply (/home/gijsn/www/ggz-zorgstandaarden/prod-2.8.20/assets/frontend/node_modules/@freshheads/webpack-config-builder/build/Builder.js:27:22)
[frontend]     at ModeAdapter.apply (/home/gijsn/www/ggz-zorgstandaarden/prod-2.8.20/assets/frontend/node_modules/@freshheads/webpack-config-builder/build/adapter/ModeAdapter.js:11:9)
[frontend]     at Builder.applyAdapter (/home/gijsn/www/ggz-zorgstandaarden/prod-2.8.20/assets/frontend/node_modules/@freshheads/webpack-config-builder/build/Builder.js:25:24)
[frontend]     at currentAdapter.apply (/home/gijsn/www/ggz-zorgstandaarden/prod-2.8.20/assets/frontend/node_modules/@freshheads/webpack-config-builder/build/Builder.js:27:22)
[frontend]     at TargetAdapter.apply (/home/gijsn/www/ggz-zorgstandaarden/prod-2.8.20/assets/frontend/node_modules/@freshheads/webpack-config-builder/build/adapter/TargetAdapter.js:11:9)
[frontend]     at Builder.applyAdapter (/home/gijsn/www/ggz-zorgstandaarden/prod-2.8.20/assets/frontend/node_modules/@freshheads/webpack-config-builder/build/Builder.js:25:24)
[frontend]     at Builder.build (/home/gijsn/www/ggz-zorgstandaarden/prod-2.8.20/assets/frontend/node_modules/@freshheads/webpack-config-builder/build/Builder.js:36:14)
[frontend]     at DefaultStackAdapter.apply (/home/gijsn/www/ggz-zorgstandaarden/prod-2.8.20/assets/frontend/node_modules/@freshheads/webpack-config-builder/build/adapter/freshheads/DefaultStackAdapter.js:74:17)
[frontend]     at Builder.applyAdapter (/home/gijsn/www/ggz-zorgstandaarden/prod-2.8.20/assets/frontend/node_modules/@freshheads/webpack-config-builder/build/Builder.js:25:24)
[frontend]     at currentAdapter^[1.apply (/home/gijsn/www/ggz-zorgstandaarden/prod-2.8.20/assets/frontend/node_modules/@freshheads/webpack-config-builder/build/Builder.js:27:22)
[frontend]     at OutputAdapter.apply (/home/gijsn/www/ggz-zorgstandaarden/prod-2.8.20/assets/frontend/node_modules/@freshheads/webpack-config-builder/build/adapter/freshheads/OutputAdapter.js:24:9)
[frontend]     at Builder.applyAdapter (/home/gijsn/www/ggz-zorgstandaarden/prod-2.8.20/assets/frontend/node_modules/@freshheads/webpack-config-builder/build/Builder.js:25:24)
[frontend]     at currentAdapter.apply (/home/gijsn/www/ggz-zorgstandaarden/prod-2.8.20/assets/frontend/node_modules/@freshheads/webpack-config-builder/build/Builder.js:27:22)
[frontend]     at EntryAdapter.apply (/home/gijsn/www/ggz-zorgstandaarden/prod-2.8.20/assets/frontend/node_modules/@freshheads/webpack-config-builder/build/adapter/EntryAdapter.js:11:9)
[frontend]     at Builder.applyAdapter (/home/gijsn/www/ggz-zorgstandaarden/prod-2.8.20/assets/frontend/node_modules/@freshheads/webpack-config-builder/build/Builder.js:25:24)
[frontend]     at Builder.build (/home/gijsn/www/ggz-zorgstandaarden/prod-2.8.20/assets/frontend/node_modules/@freshheads/webpack-config-builder/build/Builder.js:36:14)
[frontend]     at Object.<anonymous> (/home/gijsn/www/ggz-zorgstandaarden/prod-2.8.20/assets/frontend/webpack.config.js:91:24)
[frontend]     at Module._compile (/home/gijsn/www/ggz-zorgstandaarden/prod-2.8.20/assets/frontend/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
[frontend]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
[frontend]     at Module.load (internal/modules/cjs/loader.js:599:32)
[frontend]   status: 1,
[frontend]   signal: null,
[frontend]   output:
[frontend]    [ null,
[frontend]      <Buffer 7b 0a 20 20 22 6e 61 6d 65 22 3a 20 22 67 67 7a 73 74 61 6e 64 61 61 72 64 65 6e 22 2c 0a 20 20 22 70 72 6f 62 6c 65 6d 73 22 3a 20 5b 0a 20 20 20 20 ... >,
[frontend]      <Buffer 6e 70 6d 20 45 52 52 21 20 6d 69 73 73 69 6e 67 3a 20 40 66 72 65 73 68 68 65 61 64 73 2f 72 65 61 63 74 2d 66 6f 72 6d 2d 73 74 61 74 65 40 67 69 74 ... > ],
[frontend]   pid: 4943,
[frontend]   stdout:
[frontend]    <Buffer 7b 0a 20 20 22 6e 61 6d 65 22 3a 20 22 67 67 7a 73 74 61 6e 64 61 61 72 64 65 6e 22 2c 0a 20 20 22 70 72 6f 62 6c 65 6d 73 22 3a 20 5b 0a 20 20 20 20 ... >,
[frontend]   stderr:
[frontend]    <Buffer 6e 70 6d 20 45 52 52 21 20 6d 69 73 73 69 6e 67 3a 20 40 66 72 65 73 68 68 65 61 64 73 2f 72 65 61 63 74 2d 66 6f 72 6d 2d 73 74 61 74 65 40 67 69 74 ... > }
```

**Comment by gnoesiboe** [comment]
@martinbroos dit lijkt naar voren te komen zodra het dependencies zijn die direct vanaf Git binnengehaald worden. (of als ze dependencies zijn van deze dependency). Op een of andere manier detecteert ie dan niet dat ze geïnstalleerd zijn, ook al is dit wel het geval. 

Hieronder bijvoorbeeld de output van het `npm list` commando dat we gebruiken om te checken wat geinstalleerd is. Deze heeft een exit code van `1` (= error code). Als je echter goed kijkt, zie je de dependency wel in de lijst staan, waar aan het einde de warning voor gegeven wordt:

```bash
fh@e813b8690146:/projects/freshheads-besom/assets/frontend $ npm list --json --depth=0 --dev=true --prod=true
{
  "name": "freshheads-besom-frontend",
  "problems": [
    "missing: @freshheads/javascript-essentials@git+ssh://git@github.com/freshheads/freshheads-javascript-essentials.git#semver:^1.0, required by freshheads-besom-frontend@"
  ],
  "dependencies": {
    "@babel/plugin-proposal-class-properties": {
      "version": "7.10.1",
      "from": "@babel/plugin-proposal-class-properties@7.10.1",
      "resolved": "https://registry.npmjs.org/@babel/plugin-proposal-class-properties/-/plugin-proposal-class-properties-7.10.1.tgz"
    },
    "@babel/preset-env": {
      "version": "7.10.3",
      "from": "@babel/preset-env@7.10.3",
      "resolved": "https://registry.npmjs.org/@babel/preset-env/-/preset-env-7.10.3.tgz"
    },
    "@babel/preset-react": {
      "version": "7.10.1",
      "from": "@babel/preset-react@7.10.1",
      "resolved": "https://registry.npmjs.org/@babel/preset-react/-/preset-react-7.10.1.tgz"
    },
    "@babel/preset-typescript": {
      "version": "7.10.1",
      "from": "@babel/preset-typescript@7.10.1",
      "resolved": "https://registry.npmjs.org/@babel/preset-typescript/-/preset-typescript-7.10.1.tgz"
    },
    "@babel/runtime": {
      "version": "7.10.3",
      "from": "@babel/runtime@7.10.3",
      "resolved": "https://registry.npmjs.org/@babel/runtime/-/runtime-7.10.3.tgz"
    },
    "@freshheads/javascript-essentials": {
      "version": "git+ssh://git@github.com/freshheads/freshheads-javascript-essentials.git#7cea7fb92823ed0b8e1fd8eda14c880981be13b3",
      "from": "git+ssh://git@github.com/freshheads/freshheads-javascript-essentials.git#semver:^1.0",
      "resolved": "git+ssh://git@github.com/freshheads/freshheads-javascript-essentials.git#7cea7fb92823ed0b8e1fd8eda14c880981be13b3"
    },
    "@freshheads/maatcss": {
      "version": "1.0.3",
      "from": "@freshheads/maatcss@1.0.3",
      "resolved": "https://registry.npmjs.org/@freshheads/maatcss/-/maatcss-1.0.3.tgz"
    },
    "@freshheads/webpack-config-builder": {
      "version": "2.0.0",
      "from": "@freshheads/webpack-config-builder@2.0.0",
      "resolved": "https://registry.npmjs.org/@freshheads/webpack-config-builder/-/webpack-config-builder-2.0.0.tgz"
    },
    "@sentry/browser": {
      "version": "5.18.0",
      "from": "@sentry/browser@5.18.0",
      "resolved": "https://registry.npmjs.org/@sentry/browser/-/browser-5.18.0.tgz"
    },
    "@svgr/webpack": {
      "version": "5.4.0",
      "from": "@svgr/webpack@5.4.0",
      "resolved": "https://registry.npmjs.org/@svgr/webpack/-/webpack-5.4.0.tgz"
    },
    "@types/classnames": {
      "version": "2.2.10",
      "from": "@types/classnames@2.2.10",
      "resolved": "https://registry.npmjs.org/@types/classnames/-/classnames-2.2.10.tgz"
    },
    "@types/react": {
      "version": "16.9.41",
      "from": "@types/react@16.9.41",
      "resolved": "https://registry.npmjs.org/@types/react/-/react-16.9.41.tgz"
    },
    "@types/react-dom": {
      "version": "16.9.8",
      "from": "@types/react-dom@16.9.8",
      "resolved": "https://registry.npmjs.org/@types/react-dom/-/react-dom-16.9.8.tgz"
    },
    "@types/react-helmet": {
      "version": "6.0.0",
      "from": "@types/react-helmet@6.0.0",
      "resolved": "https://registry.npmjs.org/@types/react-helmet/-/react-helmet-6.0.0.tgz"
    },
    "@types/react-modal": {
      "version": "3.10.6",
      "from": "@types/react-modal@3.10.6",
      "resolved": "https://registry.npmjs.org/@types/react-modal/-/react-modal-3.10.6.tgz"
    },
    "@types/react-router-dom": {
      "version": "5.1.5",
      "from": "@types/react-router-dom@5.1.5",
      "resolved": "https://registry.npmjs.org/@types/react-router-dom/-/react-router-dom-5.1.5.tgz"
    },
    "@types/react-slick": {
      "version": "0.23.4",
      "from": "@types/react-slick@0.23.4",
      "resolved": "https://registry.npmjs.org/@types/react-slick/-/react-slick-0.23.4.tgz"
    },
    "@types/rellax": {
      "version": "1.7.3",
      "from": "@types/rellax@1.7.3",
      "resolved": "https://registry.npmjs.org/@types/rellax/-/rellax-1.7.3.tgz"
    },
    "@typescript-eslint/eslint-plugin": {
      "version": "3.4.0",
      "from": "@typescript-eslint/eslint-plugin@3.4.0",
      "resolved": "https://registry.npmjs.org/@typescript-eslint/eslint-plugin/-/eslint-plugin-3.4.0.tgz"
    },
    "@typescript-eslint/parser": {
      "version": "3.4.0",
      "from": "@typescript-eslint/parser@3.4.0",
      "resolved": "https://registry.npmjs.org/@typescript-eslint/parser/-/parser-3.4.0.tgz"
    },
    "autoprefixer": {
      "version": "9.8.4",
      "from": "autoprefixer@9.8.4",
      "resolved": "https://registry.npmjs.org/autoprefixer/-/autoprefixer-9.8.4.tgz"
    },
    "axios": {
      "version": "0.19.2",
      "from": "axios@0.19.2",
      "resolved": "https://registry.npmjs.org/axios/-/axios-0.19.2.tgz"
    },
    "babel-eslint": {
      "version": "10.1.0",
      "from": "babel-eslint@10.1.0",
      "resolved": "https://registry.npmjs.org/babel-eslint/-/babel-eslint-10.1.0.tgz"
    },
    "babel-loader": {
      "version": "8.1.0",
      "from": "babel-loader@8.1.0",
      "resolved": "https://registry.npmjs.org/babel-loader/-/babel-loader-8.1.0.tgz"
    },
    "classnames": {
      "version": "2.2.6",
      "from": "classnames@2.2.6",
      "resolved": "https://registry.npmjs.org/classnames/-/classnames-2.2.6.tgz"
    },
    "clean-webpack-plugin": {
      "version": "3.0.0",
      "from": "clean-webpack-plugin@3.0.0",
      "resolved": "https://registry.npmjs.org/clean-webpack-plugin/-/clean-webpack-plugin-3.0.0.tgz"
    },
    "copy-webpack-plugin": {
      "version": "5.1.1",
      "from": "copy-webpack-plugin@5.1.1",
      "resolved": "https://registry.npmjs.org/copy-webpack-plugin/-/copy-webpack-plugin-5.1.1.tgz"
    },
    "core-js": {
      "version": "3.6.5",
      "from": "core-js@3.6.5",
      "resolved": "https://registry.npmjs.org/core-js/-/core-js-3.6.5.tgz"
    },
    "css-loader": {
      "version": "3.6.0",
      "from": "css-loader@3.6.0",
      "resolved": "https://registry.npmjs.org/css-loader/-/css-loader-3.6.0.tgz"
    },
    "cssnano": {
      "version": "4.1.10",
      "from": "cssnano@4.1.10",
      "resolved": "https://registry.npmjs.org/cssnano/-/cssnano-4.1.10.tgz"
    },
    "eslint": {
      "version": "6.8.0",
      "from": "eslint@6.8.0",
      "resolved": "https://registry.npmjs.org/eslint/-/eslint-6.8.0.tgz"
    },
    "eslint-config-prettier": {
      "version": "6.11.0",
      "from": "eslint-config-prettier@6.11.0",
      "resolved": "https://registry.npmjs.org/eslint-config-prettier/-/eslint-config-prettier-6.11.0.tgz"
    },
    "eslint-plugin-import": {
      "version": "2.21.2",
      "from": "eslint-plugin-import@2.21.2",
      "resolved": "https://registry.npmjs.org/eslint-plugin-import/-/eslint-plugin-import-2.21.2.tgz"
    },
    "eslint-plugin-react": {
      "version": "7.20.0",
      "from": "eslint-plugin-react@7.20.0",
      "resolved": "https://registry.npmjs.org/eslint-plugin-react/-/eslint-plugin-react-7.20.0.tgz"
    },
    "eslint-plugin-react-hooks": {
      "version": "4.0.4",
      "from": "eslint-plugin-react-hooks@4.0.4",
      "resolved": "https://registry.npmjs.org/eslint-plugin-react-hooks/-/eslint-plugin-react-hooks-4.0.4.tgz"
    },
    "fibers": {
      "version": "5.0.0",
      "from": "fibers@5.0.0",
      "resolved": "https://registry.npmjs.org/fibers/-/fibers-5.0.0.tgz"
    },
    "file-loader": {
      "version": "6.0.0",
      "from": "file-loader@6.0.0",
      "resolved": "https://registry.npmjs.org/file-loader/-/file-loader-6.0.0.tgz"
    },
    "formik": {
      "version": "2.1.4",
      "from": "formik@2.1.4",
      "resolved": "https://registry.npmjs.org/formik/-/formik-2.1.4.tgz"
    },
    "lint-staged": {
      "version": "10.2.11",
      "from": "lint-staged@10.2.11",
      "resolved": "https://registry.npmjs.org/lint-staged/-/lint-staged-10.2.11.tgz"
    },
    "mini-css-extract-plugin": {
      "version": "0.9.0",
      "from": "mini-css-extract-plugin@0.9.0",
      "resolved": "https://registry.npmjs.org/mini-css-extract-plugin/-/mini-css-extract-plugin-0.9.0.tgz"
    },
    "postcss-loader": {
      "version": "3.0.0",
      "from": "postcss-loader@3.0.0",
      "resolved": "https://registry.npmjs.org/postcss-loader/-/postcss-loader-3.0.0.tgz"
    },
    "prettier": {
      "version": "2.0.5",
      "from": "prettier@2.0.5",
      "resolved": "https://registry.npmjs.org/prettier/-/prettier-2.0.5.tgz"
    },
    "react": {
      "version": "16.13.1",
      "from": "react@16.13.1",
      "resolved": "https://registry.npmjs.org/react/-/react-16.13.1.tgz"
    },
    "react-dom": {
      "version": "16.13.1",
      "from": "react-dom@16.13.1",
      "resolved": "https://registry.npmjs.org/react-dom/-/react-dom-16.13.1.tgz"
    },
    "react-helmet": {
      "version": "6.1.0",
      "from": "react-helmet@6.1.0",
      "resolved": "https://registry.npmjs.org/react-helmet/-/react-helmet-6.1.0.tgz"
    },
    "react-modal": {
      "version": "3.11.2",
      "from": "react-modal@3.11.2",
      "resolved": "https://registry.npmjs.org/react-modal/-/react-modal-3.11.2.tgz"
    },
    "react-query": {
      "version": "1.5.9",
      "from": "react-query@1.5.9",
      "resolved": "https://registry.npmjs.org/react-query/-/react-query-1.5.9.tgz"
    },
    "react-router-dom": {
      "version": "5.2.0",
      "from": "react-router-dom@5.2.0",
      "resolved": "https://registry.npmjs.org/react-router-dom/-/react-router-dom-5.2.0.tgz"
    },
    "react-slick": {
      "version": "0.26.1",
      "from": "react-slick@0.26.1",
      "resolved": "https://registry.npmjs.org/react-slick/-/react-slick-0.26.1.tgz"
    },
    "react-waypoint": {
      "version": "9.0.3",
      "from": "react-waypoint@9.0.3",
      "resolved": "https://registry.npmjs.org/react-waypoint/-/react-waypoint-9.0.3.tgz"
    },
    "rellax": {
      "version": "1.12.1",
      "from": "rellax@1.12.1",
      "resolved": "https://registry.npmjs.org/rellax/-/rellax-1.12.1.tgz"
    },
    "resolve-url-loader": {
      "version": "3.1.1",
      "from": "resolve-url-loader@3.1.1",
      "resolved": "https://registry.npmjs.org/resolve-url-loader/-/resolve-url-loader-3.1.1.tgz"
    },
    "sass": {
      "version": "1.26.9",
      "from": "sass@1.26.9",
      "resolved": "https://registry.npmjs.org/sass/-/sass-1.26.9.tgz"
    },
    "sass-loader": {
      "version": "8.0.2",
      "from": "sass-loader@8.0.2",
      "resolved": "https://registry.npmjs.org/sass-loader/-/sass-loader-8.0.2.tgz"
    },
    "sass-mq": {
      "version": "5.0.1",
      "from": "sass-mq@5.0.1",
      "resolved": "https://registry.npmjs.org/sass-mq/-/sass-mq-5.0.1.tgz"
    },
    "slick-carousel": {
      "version": "1.8.1",
      "from": "slick-carousel@1.8.1",
      "resolved": "https://registry.npmjs.org/slick-carousel/-/slick-carousel-1.8.1.tgz"
    },
    "stylelint": {
      "version": "13.6.1",
      "from": "stylelint@13.6.1",
      "resolved": "https://registry.npmjs.org/stylelint/-/stylelint-13.6.1.tgz"
    },
    "stylelint-config-prettier": {
      "version": "8.0.2",
      "from": "stylelint-config-prettier@8.0.2",
      "resolved": "https://registry.npmjs.org/stylelint-config-prettier/-/stylelint-config-prettier-8.0.2.tgz"
    },
    "stylelint-config-standard": {
      "version": "20.0.0",
      "from": "stylelint-config-standard@20.0.0",
      "resolved": "https://registry.npmjs.org/stylelint-config-standard/-/stylelint-config-standard-20.0.0.tgz"
    },
    "stylelint-order": {
      "version": "4.1.0",
      "from": "stylelint-order@4.1.0",
      "resolved": "https://registry.npmjs.org/stylelint-order/-/stylelint-order-4.1.0.tgz"
    },
    "stylelint-prettier": {
      "version": "1.1.2",
      "from": "stylelint-prettier@1.1.2",
      "resolved": "https://registry.npmjs.org/stylelint-prettier/-/stylelint-prettier-1.1.2.tgz"
    },
    "symfony-ts-router": {
      "version": "1.0.6",
      "from": "symfony-ts-router@1.0.6",
      "resolved": "https://registry.npmjs.org/symfony-ts-router/-/symfony-ts-router-1.0.6.tgz"
    },
    "terser-webpack-plugin": {
      "version": "3.0.6",
      "from": "terser-webpack-plugin@3.0.6",
      "resolved": "https://registry.npmjs.org/terser-webpack-plugin/-/terser-webpack-plugin-3.0.6.tgz"
    },
    "typescript": {
      "version": "3.9.5",
      "from": "typescript@3.9.5",
      "resolved": "https://registry.npmjs.org/typescript/-/typescript-3.9.5.tgz"
    },
    "webpack": {
      "version": "4.43.0",
      "from": "webpack@4.43.0",
      "resolved": "https://registry.npmjs.org/webpack/-/webpack-4.43.0.tgz"
    },
    "webpack-cli": {
      "version": "3.3.12",
      "from": "webpack-cli@3.3.12",
      "resolved": "https://registry.npmjs.org/webpack-cli/-/webpack-cli-3.3.12.tgz"
    },
    "webpack-stats-plugin": {
      "version": "0.3.2",
      "from": "webpack-stats-plugin@0.3.2",
      "resolved": "https://registry.npmjs.org/webpack-stats-plugin/-/webpack-stats-plugin-0.3.2.tgz"
    }
  }
}
npm ERR! missing: @freshheads/javascript-essentials@git+ssh://git@github.com/freshheads/freshheads-javascript-essentials.git#semver:^1.0, required by freshheads-besom-frontend@
```

**Comment by gnoesiboe** [comment]
De warning is van NPM zelf, en heeft eigenlijk niets te maken met de `webpack-config-builder`. De laatste voert alleen het commando `npm list --json --depth=0 --dev=true --prod=true` uit.

**Comment by gnoesiboe** [comment]
Mijn vermoeden is dat, als `@freshheads/javascript-essentials` in dit geval, in de NPM registry komt te staan, en deze module vanuit daar geinstalleerd wordt, het probleem opgelost is.

**Comment by martinbroos** [comment]
Wel vreemd als je de documentatie leest van `npm list` zou hij er wel mee om moeten kunnen gaan:

> If a project specifies git urls for dependencies these are shown in parentheses after the name@version to make it easier for users to recognize potential forks of a project.

**Comment by gnoesiboe** [comment]
@martinbroos mijn vermoeden is dat het iets te maken heeft met het feit dat dit een `private` repository is. 

maar de warning komt toch echt van het `npm list`-commando zelf..

**Comment by martinbroos** [comment]
Wanneer we deployen via Github actions klapt de deployement hier ook op uit. 
@gnoesiboe is het een idee om het valideren van modules alleen in dev mode te doen? Het voelt ergens ook wat overkill om het bij elke deploy opnieuw te checken terwijl het je alleen zou moeten helpen om de juiste modules te installeren wanneer je het project opzet. Zeker nu het problemen geeft lijkt met het wel acceptabel om het uit te zetten voor niet dev environments.

**Comment by gnoesiboe** [comment]
@martinbroos lijkt me prima voor nu
